Header + main-banner
Trudovyereservy/talent-reserves_frontend pull request #1
Opened 2023-11-14 22:10 UTC by energetikk

Всем привет! Хочу попробовать сделать первый пробный пулл реквест...  
В текущем репозитории была создана ветка main. В ней инициализирован проект.
От ветки main создал ветку develop.
От ветки develop создал ветку со своей задачей хедера и баннера. 
Хочу сделать мердж из моей ветки feature в ветку develop...

2023-11-29 15:37 UTC, DmitryStarov commented
Привет! в footer поехала верстка на 394 https://disk.yandex.ru/i/UZdUh2xzfQR-ZA https://disk.yandex.ru/i/adNHSR1W9mozsg. В input  думаю стоит добавить белый цвет вводимого текста (черный как-то совсем из общей темы макета выбивается) https://disk.yandex.ru/i/LgeOlUFhWrExDQ . Еще бы валидацию  на этот инпут сделать, там же предполагается номер телефона.

2023-11-29 16:44 UTC, AlMkin requested changes
Все хорошо, но есть недочёты о которых я написал, так же я заметил что у тебя закоменченно что-то, если это делаешь то оставляй TODO, что и почему и когда оставить или убрать, в противном случае удаляй
Ещё момент, что у тебя получилось три задачи в одном ПР, так лучше не делать и разбивать. То есть один ПР чётко решает одну проблему/ задачу - это проще ревьюить и задачи не висят подолгу в ревью, плюс у ребят из команды меньше конфликтов. В твоём ПР не должно быть ничего лишнего кроме как конкретно твоей задачи, что-то наперёд делать не надо. А так все окей - молодцом

2023-11-29 16:44 UTC, AlMkin commented on src/components/main-banner/main-banner.tsx
> +        <button className={styles.mainbanner__button}>Пример текста</button>
вот кнопка, можно так же реализовать компонент кнопки и пропсами указвать её вид и поведение

2023-11-29 16:44 UTC, AlMkin commented on src/components/main-banner/main-banner.tsx
название компонента с маленькой буквы

2023-11-29 16:44 UTC, AlMkin commented on src/components/Footer/Footer.tsx
> +            <input type="text" placeholder="Phone" className={styles.footer__input_phone} />
form, input, button  - будет лучше вынести в отдельные компоненты, и input добавить вадидацию - это все можно будет переиспользовать в других местах
старайся подходить к проектированию, как к библиотеке компонентов - это улучшить модульность, тестируемость и расширяемость

2023-11-29 16:44 UTC, AlMkin commented on src/components/Footer/Footer.tsx
> +              <li>
Там где есть списки и повторяющиеся элементы, лучше выносить это в config какой-нить и потом циклом по нему проходиться, этот же комментарий акуален и для Header - это разгрузит твой компонент

2023-12-18 22:58 UTC, energetikk commented
Всем привет! Вынес в отдельные компоненты инпуты и кнопки, сделал ссылки в футере и хедере через мап. Сделал валидацию инпута(паттерн по номеру телефона нужно вставить еще, пока просто ). Начал делать бургер-меню. Прошу посмотреть мой код на предмет: в правильном ли направлении я двигаюсь?!

2023-12-19 09:09 UTC, AlMkin commented on src/components/Header/Header.tsx
> +  const [closeMenu, setCloseMenu] = useState(false);
так как это булево значение лучше назвать как-нить isMenuOpen например

2023-12-19 09:09 UTC, AlMkin commented on src/components/Header/Header.tsx
> +    setCloseMenu(!closeMenu);
setIsMenuOpen(prevState => !prevState); - более надёжный подход, старайтесь писать так

2023-12-19 09:09 UTC, AlMkin commented on src/components/Header/Header.tsx
> +      {/* В какой компонент встатвить бургер меню?! */}
да, кажется, что бургер находится в header

а какие-могут быть ограничения? что тебя смущает?

2023-12-19 09:09 UTC, AlMkin commented on src/components/Footer/Footer.tsx
> +              {buttons[0].map((link) => (
думаю тут будет лучше поменять buttons структуру на объект - будет лучше читаться buttons.example.map

2023-12-19 09:09 UTC, AlMkin commented on src/components/Footer/Footer.tsx
> +              {buttons[0].map((link) => (
и вообще у тебя тут повторяющаяся история, лучше вынести это в отдельную функцию прям в этом компоненте, тогда мы избежим повторения

```
<ul key={index} className={styles.footer__list}>
  <h3 className={styles.footer__list_title}>{sectionName}</h3>
  {links.map((link) => (
    <LinksBlock key={link.id} linkUrl={link.linkUrl} linkText={link.linkText} />
  ))}
</ul>
```

2023-12-28 14:28 UTC, energetikk commented
Поправил замечания. Сделал Меню (пока без дизайна). Прошу посмотреть.

2023-12-28 23:05 UTC, DmitryStarov commented on src/components/Menu/Menu.tsx
> +        className={`${styles.menu__overlay} ${handler ? `${styles.menu__overlay_active}` : ''}`}
Здесь и в других местах где применяется несколько классов 
Александр рекомендовал использовать библиотеку classnames
https://www.npmjs.com/package/classnames
получится более читаемо
import classNames from 'classnames';

className={classNames(styles.menu__overlay, {[styles.menu__overlay_active]:handler, })}

2024-01-06 20:56 UTC, merged