Feature/eslint import sort
Trudovyereservy/talent-reserves_frontend pull request #11
Opened 2024-03-20 16:25 UTC by GluKosAlex

- Добавил плагин для автоматической сортировки импортов. https://github.com/lydell/eslint-plugin-simple-import-sort
- Настроил ESLint и Pettier. Указал в качестве правил, чтобы он добавлял пустую строку после всех импортов, импорты из react и next шли в самом верху, а файлы со стилями внизу
- Прогнал автоматическую сортировку всех файлов. Вызывается командой `yarn lint --fix`
- Исправил некоторые пути на алиасы next ("@"), иначе не правильно работает группировка.

2024-03-22 23:21 UTC, energetikk reviewed
В целом все ок) Просьба только, добавить правило линтера для отступа от use client 
![image](https://github.com/Trudovyereservy/frontend_part/assets/99219954/324602cc-fc77-42f3-8c71-541574fbc9ed)

2024-03-22 23:21 UTC, energetikk commented on .eslintrc.json
> +  "rules": {
Исходя из твоих комментариев к моему ПР на свайпер/тест, предлагаю внести сюда еще одно правило на отступы от строки "use client"
Что-то типа этого:
"rules": {
    "use_client_spacing": [
      "error",
      "always"
    ]
  }

2024-03-22 23:21 UTC, energetikk commented on src/components/CardsList/CardsList.tsx
> +import { testCards } from '@/utils/constatns';
Ошибка в названии файла, лишняя "t" в /constatns

2024-03-23 06:11 UTC, GluKosAlex commented on .eslintrc.json
> +  "rules": {
Привет! Добавил. Это делается с помощью правила padding-line-between-statements https://eslint.style/rules/default/padding-line-between-statements#rule-details
Посмотри, там много ещё интересных настроек для пустой линии. Может что-то ещё добавим захотим добавить.

2024-03-25 11:03 UTC, AlMkin requested changes

2024-03-25 11:03 UTC, AlMkin commented on src/components/CardsList/CardsList.tsx
> +
тут вообще улетела

2024-03-25 11:03 UTC, AlMkin commented on src/app/page.tsx
> +
Почему тут два отступа?

2024-03-25 12:52 UTC, GluKosAlex commented
@spacelessvoid, я исправил замечания и конфликты. Дополнительно добавил правило для линтера запрещающее множественные пустые строки.

2024-03-26 04:06 UTC, GluKosAlex commented on src/app/page.tsx
> +
Исправил

2024-03-26 16:22 UTC, AlMkin approved these changes

2024-03-26 16:22 UTC, merged