Swiper/test
Trudovyereservy/talent-reserves_frontend pull request #12
Opened 2024-03-20 19:59 UTC by energetikk

Переделанная версия слайдера с отзывами на главной странице сайта с использованием библиотеки SwiperJS. Компонент SwiperTest.

2024-03-21 16:33 UTC, GluKosAlex commented on src/app/page.tsx
> +'use client'
Привет! Я думаю нужно убрать эту директиву так как в этом компоненте не используются теперь хуки и его лучше оставить серверным.

2024-03-21 16:33 UTC, GluKosAlex commented on src/components/FeedbacksSlider/FeedbacksSlider.props.ts
> +import { typeFeedback } from '../../utils/models/feedback';
На проекте используются [алиасы](https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases)
Лучше придерживаться единого стиля импортов, в том числе, чтобы корректно работала их автоматическая сортировка с помощью линтера

2024-03-21 16:33 UTC, GluKosAlex commented on src/components/FeedbacksSlider/FeedbacksSlider.tsx
> +'use client';
Не сочти за душнилово, но после директивы надо добавлять пустую строку. Наверное следует добавить это правило в линтер.

2024-03-21 16:33 UTC, GluKosAlex commented on src/utils/constans.ts
>      },
Название файла осталось с опечаткой. Надо constants.ts

2024-03-22 22:34 UTC, energetikk commented on src/utils/constans.ts
>      },
Поправил в ветке Develop)

2024-03-22 23:19 UTC, energetikk commented on src/components/FeedbacksSlider/FeedbacksSlider.tsx
> +'use client';
Написал в комментарии к твоему ПР...

2024-03-23 20:22 UTC, energetikk commented on src/app/page.tsx
> +'use client'
Поправил, с помощью создания обертки SwiperProvider на компонент SwiperTest

2024-03-23 20:24 UTC, energetikk commented
Поправил все замечания указанные выше. Прошу еще раз посмотреть)

2024-03-28 22:01 UTC, energetikk commented
Поправил замечания. Посмотрите пожалуйста код компонента SwiperFeedbacks

2024-04-02 12:48 UTC, AlMkin requested changes
ветку называем feature/....
и у тебя конфликты ещё, надо подтянуть develop и прогнать линтер

2024-04-02 12:48 UTC, AlMkin commented on src/utils/models/feedback.ts
файл с типами это не utils, либо храните типы отдельно на уровне src/models
либо вместе с компонентом

2024-04-02 12:48 UTC, AlMkin commented on src/utils/constResizeWindow.ts
> +// export const customBreakpoints = {
комменты почему закоммичино или удаляем

2024-04-02 12:48 UTC, AlMkin commented on src/utils/constResizeWindow.ts
> +export const BREAKPOINT_MOBILE_MIN = 330;
не слишком ли много тут разрешений? обычно три desktop, mobile, tablet и все остальное растягивается

2024-04-02 12:48 UTC, AlMkin commented on src/components/FeedbacksSlider/FeedbacksSlider.tsx
> +const Carousel = ({ posts }: ICarouselProps) => {
файл FeedbacksSlider а тут Carousel + не вижу где это используется

2024-04-02 12:48 UTC, AlMkin commented on src/components/SwiperFeedbacks/SwiperPost/SwiperPost.tsx
> +interface ISwiperPostsProps {
у тебя уже есть нужный тип в models, из него и надо брать + сейчас у тебя в SwiperPost попадает лишнее из-за spread(...) id лишний

2024-04-02 12:48 UTC, AlMkin commented on src/components/SwiperFeedbacks/SwiperFeedbacks.tsx
> +          <SwiperSlide key={description} className="myslide">
тут есть id, и он уникальный должен быть так что в key его можно

2024-04-02 12:48 UTC, AlMkin commented on src/utils/models/feedback.ts
> +export interface typeFeedback {
TFeedpack называйте типы так

2024-04-02 12:48 UTC, AlMkin commented on src/components/SwiperFeedbacks/configSwiper.ts
> +    320: {
тут как раз и надо использовать твои константы с размерами [BREAKPOINT_MOBILE]:

2024-04-02 15:39 UTC, energetikk commented on src/components/FeedbacksSlider/FeedbacksSlider.tsx
> +const Carousel = ({ posts }: ICarouselProps) => {
Удалил этот компонент, т.к. он от старой версии свайпера и нигде не используется сейчас в коде.

2024-04-02 20:59 UTC, closed without merging