Feature/contacts components
Trudovyereservy/talent-reserves_frontend pull request #13
Opened 2024-04-02 16:53 UTC by IsaevDanil42

Добавил карту и карточки адресов на страницу контактов

2024-04-03 09:22 UTC, AlMkin requested changes

2024-04-03 09:22 UTC, AlMkin commented on src/components/Map/Map.tsx
> +export { Map };
везде импорты по default идут а тут нет, надо придерживаться единообразия

2024-04-03 09:22 UTC, AlMkin commented on src/components/ContactCards/ContactCardsList/contactCardList.module.scss
нейминг стилей тоже с большой буквы, поправь везде плз

2024-04-03 09:22 UTC, AlMkin commented on src/components/Map/Map.module.scss
> +@include netbook {}
ничего лишнего быть не должно

2024-04-03 09:22 UTC, AlMkin commented on src/components/Addresses/addressesList.module.scss
> +    gap: 20px calc(100%/3 - 286px);
давай повыносим все calc в переменные

$grid-gap: 20px;
$grid-gap-large: calc(100%/3 - 286px);
$grid-gap-xlarge: calc(100%/4 - 219px);
$grid-gap-medium: calc(100%/2 - 450px);
$side-margin-desktop: 84px;
$side-margin-mobile: 92px;

2024-04-03 09:22 UTC, AlMkin commented on src/app/contacts/page.tsx
> +  const handleAddressChange = function (mapUrl: string) {
тут стрелочки используем

2024-04-03 09:22 UTC, AlMkin commented on src/components/Addresses/AddressItem/addressItem.module.scss
> +        // width: auto;
// width: auto; ?

2024-04-06 21:04 UTC, andreiklepko88 commented on src/app/contacts/page.tsx
> +  const handleAddressChange = function (mapUrl: string) {
@AlMkin имеется в виду стрелочная функция? Скажи пожалуйста, в чём её приемущество будет?

2024-04-06 21:56 UTC, andreiklepko88 commented on src/components/Addresses/addressesList.module.scss
> +    gap: 20px calc(100%/3 - 286px);
@AlMkin получается для удобства везде лучше выносить выражения с calc в переменные?

2024-04-07 02:35 UTC, AlMkin commented on src/app/contacts/page.tsx
> +  const handleAddressChange = function (mapUrl: string) {
в функциональных компонентах используют стрелки так как это более краткий синтаксис и она улучшает читаемость и уменьшает многословность

2024-04-07 02:35 UTC, AlMkin commented on src/components/Addresses/addressesList.module.scss
> +    gap: 20px calc(100%/3 - 286px);
да, если это переиспользоваться будет то можно и в глобальные выносить
а так это улучшит читаемость

2024-04-10 21:39 UTC, IsaevDanil42 commented
Вроде поправил все замечания

2024-04-11 08:08 UTC, AlMkin approved these changes

2024-04-11 08:08 UTC, AlMkin commented on src/app/contacts/page.tsx
> +import { descriptionPages, testAddresses, testContancts } from "@/utils/constants";
где-то двойные ковычки где-то одинарные

создай задачу плз на добавление правила в линтер и возьми в работу(чтобы везде одинарные юзались),
прогони линтер по всему проекту и сделай ПР

2024-04-11 22:52 UTC, IsaevDanil42 commented on src/app/contacts/page.tsx
> +import { descriptionPages, testAddresses, testContancts } from "@/utils/constants";
Правило в линтер отдельной задачей, а эту ветку можно мерджить? Или ждать еще одобрений?

2024-04-13 12:54 UTC, AlMkin commented on src/app/contacts/page.tsx
> +import { descriptionPages, testAddresses, testContancts } from "@/utils/constants";
да, отдельной задачей

2024-04-13 12:55 UTC, merged