Feature/pagination
Trudovyereservy/talent-reserves_frontend pull request #14
Opened 2024-04-03 19:16 UTC by spacelessvoid

Добавил компоненты пагинации (стили и логику рендеринга).
Для мобильной верстки сделал допущение, что в блоке пагинации отображаются минимум 3 страницы (из макета точно не понятно, потому что видно только первую и последнюю).

2024-04-04 05:10 UTC, AlMkin requested changes
👍🏽

2024-04-04 05:10 UTC, AlMkin commented on src/components/Pagination/Pagination.module.scss
> +  background-image: $chevron;
думаю можно вынести в mixin
@mixin chevron-background($image) {
  background-image: $image;
  background-position: center;
  background-repeat: no-repeat;
}

2024-04-04 05:10 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +    function range(start: number, end: number) {
range можно вынести в utils и немного разгрузить renderPaginationItems

2024-04-04 05:10 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +  function renderPaginationItems() {
вызывать функции в return (в render функции) не желательно, в доке по react кажется есть это рекомендация

давай это завернем в useMemo

2024-04-04 05:10 UTC, AlMkin commented on src/components/Pagination/PaginationNext.tsx
> +export const PaginationNext = ({ href, currentPage, lastPage }: PaginationNextProps) => {
у тебя Next и Prev одинаковые почти, сделай один PaginationArrow и пропсом указывай направление
типа diraction="prev" | "next"

2024-04-07 04:09 UTC, AlMkin requested changes

2024-04-07 04:09 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +          {range(1, totalPages).map((page) => (
давай ещё вынесим все PaginationItem в PaginationList, чтобы разгрузить компонент
```
          {range(1, totalPages).map((page) => (
            <PaginationItem
              href={`?limit=${cardsPerPage}&page=${page}`}
              pageNumber={page}
              currentPage={currentPage}
              key={page}
            />
          ))}
```

2024-04-07 04:09 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
можно вынести в utils `?limit=${cardsPerPage}&page=${1}`

2024-04-07 04:09 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +    if (totalPages > paginationItemsToDisplay && currentPage + siblings * 2 >= totalPages) {
такие тяжелые условия тоже лучше вынести в utils

2024-04-07 04:09 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +  const cardsPerPage: number = useCardCount(width);
вот это все можно вынести в custom hook и вытащить из  него все, что нам нужно, старайся отделять бизнес логику от ui, и в идеале в компоненте не должно быть голых чисел `BREAKPOINT_TABLET ? 5 : 3` 5, 3 лучше выносить в константы

```
  const width: number = useWindowSize();
  const cardsPerPage: number = useCardCount(width);

  const paginationItemsToDisplay = width > BREAKPOINT_TABLET ? 5 : 3;

  const totalPages = Math.ceil(totalCards / cardsPerPage);
  const lastPage = totalPages;
```

2024-04-07 04:09 UTC, AlMkin commented on src/components/Pagination/PaginationItem.tsx
> +  const isSelected = pageNumber === currentPage ? true : false;
тут необязательно явно возвращать true и false, pageNumber === currentPage - достаточно

2024-04-15 04:33 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +    if (totalPages > paginationItemsToDisplay && currentPage + siblings * 2 >= totalPages) {
Вопрос по этому и предыдущему комментарию (к 58-й строке): такая дополнительная абстракция не усложнит чтение и понимание файла? 
Может быть тогда renderPaginationItems() целиком вынести в отдельный хук?

2024-04-15 05:02 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +    if (totalPages > paginationItemsToDisplay && currentPage + siblings * 2 >= totalPages) {
нет, только улучшит если красиво назовешь, так как у тебя тут аж 5 операторов, больше трёх уже можно выносить
по 58, не критично, но я бы вынес, принцип DRY ещё не отменяли) проще будет если захочется, что-то изменить/добавить, в одном месте сделаешь, а не в нескольких

по поводу renderPaginationItems: я наверху оставил коммент, что можно вынести PaginationItem в List, в хуки мы все таки выносим больше логику
по итогу у тебя в Pagination останется только условия отрисовки ui, а логику и повторяющиеся вещи выносим

2024-04-16 12:12 UTC, GluKosAlex commented on src/components/Pagination/Pagination.module.scss
> +$chevron-inverse: url('../../../public/chevron\ .\ arrows.grey.svg');
Имена файлов с пробелами и точками выглядят жутковато. В путях приходится экранировать и читается это не очень. Я бы посоветовал унифицировать именование файлов или в snake_case, или в kebab-case, или аля по БЭМ (chevron-arrows.svg, chevron-arrows__active.svg)

2024-04-16 12:12 UTC, GluKosAlex commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Возможно, PaginationItem придётся сделать не ссылкой, а кнопкой, тк будет вызываться функция с фетчем, которая будет принимать limit и page, и передавать их в запрос в качестве query параметров. Или ссылке придутся указывать onClick и пресекать дефолтное поведение.

2024-04-23 19:13 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Не стал выносить в `utils`, потому что строки немного разные в зависимости от условий. Повторяющаяся строка была внутри PaginationItem и ушла в PaginationList в единственном экземпляре

2024-04-23 19:15 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +    if (totalPages > paginationItemsToDisplay && currentPage + siblings * 2 >= totalPages) {
В итоге тоже не вынес в `utils`, потому что это потребовало бы импортировать переменные, которые высчитваются в компоненте - посчитал это нецелесообразным.
Но вынес условия в константы внутри компонента для чуть лучшей читаемости

2024-04-23 19:18 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Пока что не стал переделывать в кнопку, потому что `Link` использовал подразумевая, что элементы будут листаться без полного перерендера страницы. Но, возможно, так не получится сделать - я себе этот момент отметил, чтобы в будущем вернуться к этому и, если что, переделать в кнопку

2024-04-24 13:17 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +  const ellipsisNotVisible = totalPages <= paginationItemsToDisplay;
разбивай сложные условия на более простые логические переменные, не больше трёх условий + нейминг

`const isPaginationNecessary = totalPages > paginationItemsToDisplay;
const isCurrentPageNearEnd = currentPage + siblingCount * 2 >= totalPages;
const isCurrentPageNearStart = currentPage <= siblingCount + 2;
const isCurrentPageAwayFromBothEnds = currentPage > siblingCount * 2 + 1;

const ellipsisNotVisible = !isPaginationNecessary;
const ellipsisLeftVisible = isPaginationNecessary && isCurrentPageNearEnd;
const ellipsisRightVisible = isPaginationNecessary && isCurrentPageNearStart;
const ellipsisLeftAndRightVisible = isPaginationNecessary && isCurrentPageAwayFromBothEnds;`

2024-04-24 13:17 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +  const ellipsisNotVisible = totalPages <= paginationItemsToDisplay;
https://refactoring.com в книге Fowler-a можно найти полезные техники

2024-04-24 13:17 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +  const siblings = (paginationItemsToDisplay - 3) / 2;
const ANY_MAGIC_NUMBER = 3; // Должно пояснять что за '3'

const siblings = (paginationItemsToDisplay - ANY_MAGIC_NUMBER) / 2;

и тут Math.floor не надо?

2024-04-24 13:17 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
тут я имел ввиду просто

export function createPaginationUrl(cardsPerPage, page) {
  return `?limit=${cardsPerPage}&page=${page}`;
}

кажется он везде одинаковый

2024-04-24 13:17 UTC, AlMkin commented on src/components/Pagination/PaginationArrow.tsx
> +
вот это все:
`  const isNextDisabled = currentPage === lastPage;
  const isPreviousDisabled = currentPage === 1;
  const isDisabled =
    (isNextDisabled && direction === 'next') || (isPreviousDisabled && direction === 'previous');

  const chevronStyle =
    direction === 'next' ? styles.pagination__chevron : styles.pagination__chevronInverse;
  const chevronDisabledStyle =
    direction === 'next'
      ? styles.pagination__chevron_disabled
      : styles.pagination__chevronInverse_disabled;`

можно сократить тут до:

const isDisabled = getIsDisabled(direction, currentPage, lastPage);
const chevronStyles = getChevronStyles(direction, isDisabled);

2024-04-25 14:24 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Не совсем так: он был одинаковый в нескольких местах, но теперь именно в таком виде строчка только в компоненте PaginationList, в других немного разные вариации. Как функция, возвращающая строку, будет работать, в принципе, но, опять же, по-моему излишняя абстракция.
![image](https://github.com/Trudovyereservy/frontend_part/assets/55495/8976221e-3589-42c0-80c6-b83626102597)

2024-04-25 14:44 UTC, spacelessvoid commented on src/components/Pagination/PaginationArrow.tsx
> +
Ты имеешь ввиду, что `getIsDisabled` и `getChevronStyles` нужно сделать функциями, которые возвращают соответствующие условия?

2024-04-25 15:01 UTC, AlMkin commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
я говорю про то что у тебя строка одинаковая, ты туда просто передаешь limit и page

сейчас может показаться как лишняя абстракция, но это не так
потом придут к тебе и попросят добавить ещё один какой-то параметр, а потом ещё придут и добавить надо будет сортировку какую-нить это ещё пара параметров, а потом переименовать может какую нить параметр захочется, чтобы с другим конектилось и тебе уже не в одном месте все это менять придётся

в общем, по моему опыту это надо выносить

2024-04-25 15:03 UTC, AlMkin commented on src/components/Pagination/PaginationArrow.tsx
> +
ага, сразу полегче будет компонент

2024-04-28 04:07 UTC, GluKosAlex commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Link - это хорошо, но он для роутинга по приложению. У нас по запросу с данными урлами + квери параметрами на апи бэка приходит объект с пагинированным массивом, который надо будет отрисовать. Я тебя просто хочу предостеречь от лишней работы. Ты сейчас повыносишь всякие там методы по генерации урлов в отдельные файлы, а они по сути не понадобятся, так как тебе всего лишь придётся вызвать сервер акшн по онКлик и передать туда несколько параметров, включающих в себя лимит и номер страницы. Просто напоминаю - у нас пагинация на стороне бэка.

2024-04-29 13:50 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
Я в итоге вообще зарефакторил эту часть =) Осталось `href={'?page=${1}'}`
Решил, что в ссылке не нужен параметр `limit`, мы его можем в компоненте расчитывать и передавать функции, которая делает запрос на сервер.

2024-04-29 14:05 UTC, spacelessvoid commented on src/components/Pagination/Pagination.tsx
> +          <PaginationItem href={`?limit=${cardsPerPage}&page=${1}`} pageNumber={1} />
В итоге методы по генерации урлов я пока не наделал =) Думаю, они и не нужны будут.
Спасибо за предостережения, Кость (без иронии).
Меня твой коммент снова навел на мысли о том, как данные должны приходить и я нарисовал схемку, чтобы не забыть.
По сути, нажимая на ссылку, мы ничего никуда не отправляем - это не нужно. У нас загоняются параметры в адресную строку, а страница на основе этого обращается на сервер за контентом.
Насколько я понимаю, это вполне себе в рамках парадигмы Некста.
Только у нас страницы 'use client', а мне кажется что должны быть серверные.

Схема (рисовал для себя, поэтому не пытался сильно понятно сделать):
![2024-04-29 - TR-data-fetching](https://github.com/Trudovyereservy/frontend_part/assets/55495/2103bd4d-4cc4-4f90-969f-9c3579800d23)

2024-05-02 03:39 UTC, AlMkin approved these changes

2024-05-02 16:08 UTC, merged