Feature/cards news
Trudovyereservy/talent-reserves_frontend pull request #17
Opened 2024-04-14 21:02 UTC by energetikk

![2024-04-14_22-51-09](https://github.com/Trudovyereservy/frontend_part/assets/99219954/73c74e58-c4b0-4946-8ad2-819e8d04f1fa)
Карточки новостей на главной странице.
ПР на проверку.

2024-04-16 12:19 UTC, GluKosAlex requested changes
Везде по коду заменены одинарные кавычки на двойные. У нас в конфиге Prettier указано правило использовать одинарные.

2024-04-17 20:03 UTC, energetikk commented
Посмотрите еще разок. Поправил замечания

2024-04-23 17:28 UTC, spacelessvoid commented on src/components/CardsNews/CardsNews.tsx
> +  const resizeListener = () => {
У нас есть хук useWindowSize - думаю, можно было бы переработать эту часть, чтобы использовать его вместо локальной функции

2024-04-23 17:32 UTC, spacelessvoid commented on src/components/CardsNews/CardsNews.module.scss
> +  height: 300px;
Я бы не стал для контейнера использовать фиксированную высоту: карточки могут уехать на второй ряд, либо стать больше. Лучше заменить на `min-height`, на мой взгляд

2024-05-02 20:26 UTC, energetikk commented
Замечания устранил. Посмотрите еще разок плиз...

2024-05-03 12:57 UTC, spacelessvoid commented on src/app/coachs/page.tsx
> +        <meta name="title" content="Блог" />
Я так предполагаю, тут значение `content` должно быть такое же, как внутри `<title></title>` - "Тренерский состав"

2024-05-03 12:58 UTC, spacelessvoid commented on src/app/contacts/page.tsx
>          <meta name="title" content="Блог" />
И тут - "Контакты"

2024-05-03 12:58 UTC, spacelessvoid commented on src/app/news/page.tsx
> +        <meta name="title" content="Блог" />
И тут - "Новости"

2024-05-04 04:56 UTC, GluKosAlex approved these changes

2024-05-12 14:17 UTC, merged