Feature/news card
Trudovyereservy/talent-reserves_frontend pull request #19
Opened 2024-04-18 22:05 UTC by andreiklepko88

2024-05-03 23:02 UTC, energetikk reviewed
Привет, Андрей!) Оставил несколько некритичных замечаний в коде)

2024-05-03 23:02 UTC, energetikk commented on src/components/NewsCards/NewsCard/NewsCard.module.scss
> +@import '../../../styles/_variables.scss';
Вместо длинных путей можно попробовать воспользоваться алиасами через "@"

2024-05-03 23:02 UTC, energetikk commented on src/components/NewsCards/NewsCardsList/NewsCardsList.tsx
> +import { NewsCard } from "../NewsCard/NewsCard";
В проекте используем одинарные кавычке во всех местах. Линтер настроен на одинарные кавычки. Можно пробежаться в автоматическом режиме с помощью скрипта yarn lint --fix. Только предварительно подтяни ветку develop и пофикси конфликты

2024-05-03 23:02 UTC, energetikk commented on src/app/news/page.tsx
> +      <NewsCardsList newsCards={newsCards} />
На всех разрешениях меньше 1440 по три столбика карточки расположены... На разрешении ниже 768 уже не совсем красиво смотрятся вытянутые карточки и подписи к ним... https://disk.yandex.ru/d/OpPFdhjnkyzk3A
А так же отображается 8 карточек из 9 возможных https://yadi.sk/d/5mWBwrn37aQBNA, я бы сделал, если отображается по девять карточек, то три ряда, а если по 8 карточек на странице, то четное число рядов, что бы была заполнена вся "сетка"

2024-05-03 23:02 UTC, energetikk commented on src/components/NewsCards/NewsCardsList/NewsCardsList.tsx
> +    const count = useCardCount(width);
Здесь нужно будет добавить в функции useCardCount второй аргумент. значение "строковое", например 'newsCardsComponent'

2024-05-03 23:02 UTC, energetikk commented on src/components/NewsCards/NewsCard/NewsCard.props.tsx
> +    id?: number;
думаю, что можно id и время публикации сделать обязательными, т.к. по идее должны быть у каждой новости

2024-05-03 23:02 UTC, energetikk commented on src/utils/constants.ts
> +  id?: number;
тут тоже id обязательным можно сделать

2024-05-07 16:42 UTC, IsaevDanil42 commented on src/components/NewsCards/NewsCard/NewsCard.props.tsx
> +    id?: number;
Вообще, если я всё правильно понял, там все поля обязательны. Ну и поля tags и images - это массивы
![image](https://github.com/Trudovyereservy/frontend_part/assets/102398865/7e0ffd45-ec2d-4295-9a24-4c4d3b30b25d)

2024-05-12 21:47 UTC, andreiklepko88 commented on src/components/NewsCards/NewsCardsList/NewsCardsList.tsx
> +    const count = useCardCount(width);
Привет, добавил, но не понимаю для чего. В хуке useCardCount у нас один аргумент - ширина. Объясните пожалуйста)

2024-05-25 15:49 UTC, andreiklepko88 commented
Картинки пока оставил строкой, нужно будет исправить при подключении бэкенда.

2024-05-27 11:52 UTC, AlMkin requested changes

2024-05-27 11:52 UTC, AlMkin commented on package-lock.json
package-lock удаляем, только yarn

2024-05-27 11:52 UTC, AlMkin commented on frontend_part
лишняя директория

2024-07-15 19:44 UTC, merged