Feature/faq
Trudovyereservy/talent-reserves_frontend pull request #3
Opened 2023-11-22 15:51 UTC by DmitryStarov

задача https://www.notion.so/feedbacks-a5153291104c43a7a424c06307dae040?pvs=4
компонент назвал Faq, а не feedbacks, т.к. в макете этот блок называется FAQ

2023-11-27 20:28 UTC, energetikk commented
Чуть-чуть не совпадает разметка на 394px, https://yadi.sk/d/R_6oH4RjHHbZgA
В остальном всё гуд)

2023-11-30 15:39 UTC, DmitryStarov commented
Привет! Внес правки по замечаниям

2023-12-17 13:47 UTC, energetikk commented
Недочеты устранены. Все ок!)

2023-12-19 08:31 UTC, AlMkin requested changes
Все хорошо, несколько небольших правок

2023-12-19 08:31 UTC, AlMkin commented on src/components/FaqItem/FaqItem.tsx
> +    setIsItemOpened(!isItemOpened);
будет лучше использовать setIsItemOpened(prevState => !prevState)

2023-12-19 08:31 UTC, AlMkin commented on src/components/FaqItem/FaqItem.tsx
> +const FaqItem = (faqItems: FaqItemProps) => {
лучше диструктуризировать пропсы { title, text }: FaqItemProps, будет более понятно с чем имеем дело

2023-12-19 08:31 UTC, AlMkin commented on src/components/FaqItem/FaqItem.tsx
> +        className={`${styles.faqitem__wrapper} ${isItemOpened ? styles.faqitem__wrapper_open : ''}`}
давай будем использовать classnames для классов, будет выглядеть более чище

import classNames from 'classnames';

className={classNames(styles.faqitem__wrapper, {
  [styles.faqitem__wrapper_open]: isItemOpened,
})}

2023-12-19 08:31 UTC, AlMkin commented on src/components/Faq/Faq.tsx
> +const Faq = () => {
после импортов добавляйте отступы и лучше это правило в линтер добавть, можно создать задачку отдельную на это

2023-12-19 08:31 UTC, AlMkin commented on src/components/Faq/Faq.tsx
> +        {testFaqItems.map( (elem) => (
тут тоже можно диструктурить { titile, text, id }

2023-12-20 16:15 UTC, DmitryStarov commented
внес исправления по всем замечаниям

2023-12-21 05:19 UTC, DmitryStarov commented on src/components/Faq/Faq.tsx
> +const Faq = () => {
добавил правило для eslint ПР4 https://github.com/Trudovyereservy/frontend_part/pull/4

2023-12-25 09:33 UTC, AlMkin approved these changes
коммент и аппрув

2023-12-25 09:33 UTC, AlMkin commented on src/components/FaqItem/FaqItem.tsx
> +            isItemOpened ? styles.faqitem__button_active : ''
тут пропустил, можно тоже classNames

2023-12-25 15:13 UTC, merged