Feature/coach card
Trudovyereservy/talent-reserves_frontend pull request #9
Opened 2024-02-15 21:12 UTC by energetikk

Сделал блок карточек тренеров.

2024-02-16 17:47 UTC, AlMkin requested changes

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/Card/Card.module.scss
> +.card__directions {
.card__directions, .card__achievements {
font-size: 15px;
font-weight: 500;
line-height: 170%;
margin-top: 8px;
}

.card__achievements {
margin-top: 47px;
}

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/Card/Card.module.scss
> +  border: #839ead 1px solid;
Цвета и все что повторяется можно вынести в переменные

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/Card/Card.tsx
> +    setOpenInfo(!openInfo);
setOpenInfo((prevState) => !prevState); - хорогая практика

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/CoachList/CoachList.tsx
> +  useEffect(() => {
тут будет лучше заюзать useMemo и убрать useState и useEffect, вынести  в константу размеры экрана, и можно еще switch case вместо if
а еще лучше будет вынести это в custom hook например useCardCount в utils, и 8 и 9 тоже в константы перед хуком

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/CoachList/CoachList.tsx
> +  useEffect(() => {
по итогу в компоненте останется const count = useCardCount();

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/CoachList/CoachList.tsx
> +import { ICardCoachProps } from '../Card/Card.props';
Добавьте задачку плз, чтобы добавить правило на сортировку импортов

2024-02-16 17:47 UTC, AlMkin commented on src/components/CoachCards/CoachList/CoachList.tsx
> +            key={card.id}
в coachCards нет id, и сделай constants.js -> ts плз (js не юзаем)

2024-02-29 19:51 UTC, energetikk commented
Всем привет! Прошу посмотреть исправленную версию кода.

2024-03-01 10:16 UTC, AlMkin approved these changes

2024-03-02 20:20 UTC, merged